version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  webhook:
    build: ./webhook
    container_name: webhook_service
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./webhook:/webhook

volumes:
  rabbitmq_data: {}
