bot:
  token: "bot token"        # Токен бота от BotFather
  webhook_url: "https://example.com/webhook"  # URL вебхука

server:
  host: "0.0.0.0"
  port: 8080

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "guest"
  password: "guest"
  queue: "bot_events"