bot:
  token: "8425361906:AAGf6OIP-owwcb-erbhg2bjEo6i_redg2Ao"
  username: "jsdcjsdmidewombot"

server:
  host: "0.0.0.0"
  port: 8081

game:
  min_players: 1
  max_players: 5

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "guest"
  password: "guest"
  queue: "bot_events"

redis:
  url: "redis://redis:6379/0" 

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres_pass
  database: db_game