[project]
name = "rmq-core"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "aio-pika==9.5.7",
]

[tool.uv]

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff]
extend = "../pyproject.toml"