server:
  host: "0.0.0.0"
  port: 8082

admin:
  email: "admin@admin.ru"
  password: "jdscjdmJe9w9eKKkcmsc"

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres_pass
  database: db_game

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=