bot:
  token: "8425361906:AAGf6OIP-owwcb-erbhg2bjEo6i_redg2Ao"

server:
  host: "0.0.0.0"
  port: 8082

admin:
  email: "admin@admin.ru"
  password: "jdscjdmJe9w9eKKkcmsc"

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres_pass
  database: db_game