name: Check dev
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install ruff
        run: pip install ruff==0.4.2
      - run: ruff format --check && ruff check --no-fix

  test_api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_pass
          POSTGRES_DB: test_db_game
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install UV
        run: curl -fsSL https://astral.sh/uv/install.sh | sh
      - name: Setup UV environment
        working-directory: api
        run: |
          uv venv
          uv sync --no-interaction
      - name: Run tests
        working-directory: api
        run: uv run pytest

  test_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install UV
        run: curl -fsSL https://astral.sh/uv/install.sh | sh
      - name: Setup UV environment
        working-directory: webhook
        run: |
          uv venv
          uv sync --no-interaction
      - name: Run tests
        working-directory: webhook
        run: uv run pytest
