[project]
name = "tg-client"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "aiohttp==3.12.15",
]

[tool.uv]

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff]
extend = "../pyproject.toml"